### ISSUE TITLE
Time out after 180 seconds

### ISSUE THREAD

**Issue by randyzwitch** [cloudera/clusterdock#2]
I've tried both the two node and multi-node examples from the blog post, both times I got a time out error (on OSX)

```
$ clusterdock_run ./bin/start_cluster cdh
Password:
latest: Pulling from cloudera/clusterdock

5c68a10e9f3f: Pull complete 
f07225d2e159: Pull complete 
45d84e245454: Pull complete 
188296d937c8: Pull complete 
Digest: sha256:d3ed2cfd25391e052d668d56aca4f1f45ec552691669f4ea77736d541aabcab6
Status: Downloaded newer image for cloudera/clusterdock:latest
INFO:clusterdock.topologies.cdh.actions:Pulling image docker.io/cloudera/clusterdock:cdh580_cm581_primary-node. This might take a little while...
cdh580_cm581_primary-node: Pulling from cloudera/clusterdock

3eaa9b70c44a: Pull complete 
99ba8e23f310: Pull complete 
c9c08e9a0d03: Pull complete 
7434a9a99daa: Pull complete 
d52d9baa0ee6: Pull complete 
00ca224ba661: Pull complete 
Digest: sha256:396def25dbba0a9a9f371f52ed79c2266fdc451303a6bea728fe4625326b4537
Status: Downloaded newer image for cloudera/clusterdock:cdh580_cm581_primary-node
INFO:clusterdock.topologies.cdh.actions:Pulling image docker.io/cloudera/clusterdock:cdh580_cm581_secondary-node. This might take a little while...
cdh580_cm581_secondary-node: Pulling from cloudera/clusterdock

3eaa9b70c44a: Already exists 
99ba8e23f310: Already exists 
c9c08e9a0d03: Already exists 
7434a9a99daa: Already exists 
d52d9baa0ee6: Already exists 
f70deff0592f: Pull complete 
Digest: sha256:6cdec6848ca6ed1d9a13174cb169762ae2103ff048d58cdc99f5d9aaecad00a6
Status: Downloaded newer image for cloudera/clusterdock:cdh580_cm581_secondary-node
INFO:clusterdock.cluster:Network (cluster) not present, creating it...
INFO:clusterdock.cluster:Successfully setup network (name: cluster).
INFO:clusterdock.cluster:Successfully started node-2.cluster (IP address: 192.168.123.3).
INFO:clusterdock.cluster:Successfully started node-1.cluster (IP address: 192.168.123.2).
INFO:clusterdock.cluster:Started cluster in 7.22 seconds.
INFO:clusterdock.topologies.cdh.actions:Changing server_host to node-1.cluster in /etc/cloudera-scm-agent/config.ini...
INFO:clusterdock.topologies.cdh.actions:Restarting CM agents...
cloudera-scm-agent is already stopped
Starting cloudera-scm-agent: [  OK  ]
Stopping cloudera-scm-agent: [  OK  ]
Starting cloudera-scm-agent: [  OK  ]
INFO:clusterdock.topologies.cdh.actions:Waiting for Cloudera Manager server to come online...
Traceback (most recent call last):
  File "./bin/start_cluster", line 70, in <module>
    main()
  File "./bin/start_cluster", line 63, in main
    actions.start(args)
  File "/root/clusterdock/clusterdock/topologies/cdh/actions.py", line 109, in start
    CM_SERVER_PORT, timeout_sec=180)
  File "/root/clusterdock/clusterdock/utils.py", line 52, in wait_for_port_open
    timeout_sec, address, port
Exception: Timed out after 180 seconds waiting for 192.168.123.2:7180 to be open.
```

**Comment by dimaspivak** [comment]
Hm, how much memory/CPU do you have allocated for this in your Docker for Mac instance? Since the containers were successfully started, it looks like networking works, but it might be that you don't have adequate resources to support Cloudera Manager.

**Comment by randyzwitch** [comment]
I am using 12 cores/ 32GB.

As it turned out, restarting Docker for Mac appears to have fixed it.

Thanks for creating this! Looking forward to banging around on it (can't just willy-nilly change things in our production cluster)
