### ISSUE TITLE
Sorry,I got this issue: Error getting directory attributes

### ISSUE THREAD

**Issue by RoryLiuwenxuan** [cloudera/clusterdock#36]
[19/Apr/2018 17:41:47 +0000] 4917 Monitor-HostMonitor throttling_logger ERROR    Error getting directory attributes for /opt/cm-5.14.0/log/cloudera-scm-agent
Traceback (most recent call last):
  File "/opt/cm-5.14.0/lib64/cmf/agent/build/env/lib/python2.7/site-packages/cmf-5.14.0-py2.7.egg/cmf/monitor/dir_monitor.py", line 90, in _get_directory_attributes
    name = pwd.getpwuid(uid)[0]
KeyError: 'getpwuid(): uid not found: 1106'
[19/Apr/2018 17:41:47 +0000] 4917 MainThread agent        ERROR    Heartbeating to 172.16.21.22:7182 failed.
Traceback (most recent call last):
  File "/opt/cm-5.14.0/lib64/cmf/agent/build/env/lib/python2.7/site-packages/cmf-5.14.0-py2.7.egg/cmf/agent.py", line 1419, in _send_heartbeat
    self.master_port)
  File "/opt/cm-5.14.0/lib64/cmf/agent/build/env/lib/python2.7/site-packages/avro-1.6.3-py2.7.egg/avro/ipc.py", line 469, in __init__
    self.conn.connect()
  File "/usr/lib64/python2.7/httplib.py", line 807, in connect
    self.timeout, self.source_address)
  File "/usr/lib64/python2.7/socket.py", line 571, in create_connection
    raise err
error: [Errno 111] Connection refused

**Comment by RoryLiuwenxuan** [comment]
Can someone help me? thanks

**Comment by dimaspivak** [comment]
Not a clusterdock issue.
